Traceback (most recent call last):
  File "/home/pf657206/general-env/lib/python3.10/site-packages/smac/facade/abstract_facade.py", line 322, in optimize
    incumbents = self._optimizer.optimize(data_to_scatter=data_to_scatter)
  File "/home/pf657206/general-env/lib/python3.10/site-packages/smac/main/smbo.py", line 317, in optimize
    self._add_results()
  File "/home/pf657206/general-env/lib/python3.10/site-packages/smac/main/smbo.py", line 441, in _add_results
    self.tell(trial_info, trial_value)
  File "/home/pf657206/general-env/lib/python3.10/site-packages/smac/main/smbo.py", line 236, in tell
    self.save()
  File "/home/pf657206/general-env/lib/python3.10/site-packages/smac/main/smbo.py", line 427, in save
    with open(str(path / "optimization.json"), "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'smac_output_test_normalized/af99d7f2aa3c6296b028cfd465f43c79/42/optimization.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rwthfs/rz/cluster/home/pf657206/Dokumente/BT/fid_specific_switching/scripts/switch_model_optimization.py", line 230, in <module>
    main()
  File "/rwthfs/rz/cluster/home/pf657206/Dokumente/BT/fid_specific_switching/scripts/switch_model_optimization.py", line 187, in main
    best_config = smac.optimize()
  File "/home/pf657206/general-env/lib/python3.10/site-packages/smac/facade/abstract_facade.py", line 324, in optimize
    self._optimizer.save()
  File "/home/pf657206/general-env/lib/python3.10/site-packages/smac/main/smbo.py", line 427, in save
    with open(str(path / "optimization.json"), "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'smac_output_test_normalized/af99d7f2aa3c6296b028cfd465f43c79/42/optimization.json'
